Separate CR bump and reduced passes
brave/qa-resources pull request #402
Opened 2022-02-22 17:10 UTC by LaurenWags

Fix #401

- Created wikitemplate-ReducedDesktop.md
- Created wikitemplate-ReducedAndroid.md
- Updated wikitemplate-minorCRbumpDesktop.md
- Updated wikitemplate-minorCRbumpAndroid.md
- Updated brave_testrun_generator.py to use wikitemplate-ReducedDesktop.md and wikitemplate-ReducedAndroid.md

2022-02-23 06:05 UTC, stephendonner commented on brave_testrun_generator.py
> +    AndroidARMtitle = "Manual test run on Android ARM  for " + milestonever
Possible nit: is this extra space intended?  `ARM [two spaces] for `?

2022-02-23 06:06 UTC, stephendonner commented on brave_testrun_generator.py
> +    AndroidTabtitle = "Manual test run on Android Tab  for " + milestonever
Possible nit: is this extra space intended?  `Android Tab [two spaces] for `?

2022-02-23 06:11 UTC, stephendonner approved these changes
++

Note that I defer to @kjozwiak / @srirambv for final r, since I haven't-yet had a chance to set this up via Python and give it a whirl (will do so tomorrow, but didn't want to delay this merge).

2022-02-23 12:56 UTC, srirambv approved these changes
++.

Just the minor nits that @stephendonner pointed. Apart from that looks good. Awesome job on the script update. :+1:

2022-02-24 01:13 UTC, kjozwiak requested changes
Awesome job @LaurenWags but looks like there's an issue with not being enable to generate IPFS or Tor passes as per:

![image](https://user-images.githubusercontent.com/2602313/155437543-29a2c91c-5b85-40cc-9516-e7a0b2e3a05a.png)

![image](https://user-images.githubusercontent.com/2602313/155437490-dd97627d-a648-4a08-97a6-de7a47774928.png)

Assuming it's due to adding the two new `Basic` selections which probably offset the last two on the list.

2022-02-24 03:56 UTC, srirambv commented
For Tor and IPFS you need to type in the name not the selection number. There is a note added above the selection to type in

2022-02-24 13:52 UTC, LaurenWags commented
@kjozwiak I see the same as @srirambv when typing tor or ipfs instead of numbers.

<img width="737" alt="Screen Shot 2022-02-24 at 8 50 33 AM" src="https://user-images.githubusercontent.com/28145373/155536573-f1a548fe-dcfc-4e47-907a-017688511383.png">

are the numbers confusing? I could remove them for tor/ipfs if you'd prefer. I kept them since they were there previously, but can change if that's better. Could make the list something like:

```
1. Desktop Release (Full manual pass)
2. Desktop Release (Reduced manual pass for Hotfix)
3. Desktop Release (Basic checks for minor Chromium bump)
4. Android Release (Full manual pass)
5. Android Release (Reduced manual pass for Hotfix)
6. Android Release (Basic checks for minor Chromium bump)
7. iOS Release
Tor
IPFS
```

2022-02-24 16:09 UTC, srirambv commented
I think we can leave it as is. Its been like this for a while when the script was redone. also has a note on top as well to indicate it

2022-02-24 19:35 UTC, kjozwiak approved these changes
LGTM 👍 Apologies for the noise! For some reason, I thought we used the numbers to indicate IPFS/Tor but as @srirambv pointed out, you have to specifically type out either `ipfs` or `tor`

2022-02-24 19:47 UTC, merged